force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Vacancy_opening_date__c.field-meta.xml
<CustomField>
    <fullName>Vacancy_opening_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Vacancy opening date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {
            
    public static List<Position__c> createPositions(Integer numPos, String status, Boolean doInsert){
        List<Position__c> positions = new List<Position__c>();
        for(Integer i=0;i<numPos;i++) {
                Position__c pos = new Position__c(Name = 'Test position ' + i, Status__c = status, Vacancy_opening_date__c = date.today().addDays(-91));
                positions.add(pos);
        }
        if (doInsert) {
            insert positions;
        }
        return positions;
    }
}