force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionProcessorTest.cls
@isTest
private class PositionProcessorTest {
    @isTest 
    static void test() {
        Position__c[] positions = TestDataFactory.createPositions(20, 'Open', true);
        
        Test.startTest();
        PositionProcessor posProc = new PositionProcessor();
        Database.executeBatch(posProc);
        Test.stopTest();

        System.debug('positions ----->' + [SELECT Name, Status__c  FROM Position__c]);
        System.assertEquals(20, [SELECT count() FROM Position__c WHERE Status__c = 'Closed']);
    }
}