force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Vacancy_opening_date__c.field-meta.xml
<CustomField>
    <fullName>Vacancy_opening_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Vacancy opening date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PositionProcessor.cls
public class PositionProcessor implements Database.Batchable<sObject>{
        public Database.QueryLocator start(Database.BatchableContext bc) {
            return Database.getQueryLocator(
                'SELECT Id FROM Position__c WHERE Vacancy_opening_date__c < LAST_90_DAYS' 
            );
        }
        public void execute(Database.BatchableContext bc, List<Position__c> scope){
            List<Position__c> positionList = new List<Position__c>();
            for (Position__c position : scope) {
                    position.Status__c = 'Closed';
                    positionList.add(position); 
            }
            update positionList;
        }
        public void finish(Database.BatchableContext bc){
            
        }
}