force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Application_deadline__c.field-meta.xml
<CustomField>
    <fullName>Application_deadline__c</fullName>
    <label>Application deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Max_Salary__c.field-meta.xml
<CustomField>
    <fullName>Max_Salary__c</fullName>
    <label>Max Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Min_Salary__c.field-meta.xml
<CustomField>
    <fullName>Min_Salary__c</fullName>
    <label>Min Salary</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Vacancy_opening_date__c.field-meta.xml
<CustomField>
    <fullName>Vacancy_opening_date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Vacancy opening date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PositionController.cls
public with sharing class PositionController {
    public String selectStatus {get;set;}
    public List<Position__c> positions {get;set;}

  public positionController() {
      positions = [SELECT Name, Status__c, Vacancy_opening_date__c, Application_deadline__c, Min_Salary__c, Max_Salary__c 
                  FROM Position__c 
                  ORDER BY Name];
  }
  
  public List<Position__c> getPosition() {
      return positions; 
  }

  public List<SelectOption> getStatusList(){
    List<SelectOption> options = new List<SelectOption>();
    options.add(new SelectOption('All','All'));
    Schema.DescribeFieldResult fieldResult = Position__c.Status__c.getDescribe();
      for(Schema.PicklistEntry getStatus : fieldResult.getPicklistValues()){
        options.add(new SelectOption(getStatus.getLabel(), getStatus.getValue()));
      }
      return options;
  }
  
  public void getFilteredStatus() {
    if(selectStatus == 'All') {
      positions = [SELECT Name, Status__c, Vacancy_opening_date__c, Application_deadline__c, Min_Salary__c, Max_Salary__c 
                  FROM Position__c
                  ORDER BY Name];
    } else {
      positions = [SELECT Name, Status__c, Vacancy_opening_date__c, Application_deadline__c, Min_Salary__c, Max_Salary__c 
                  FROM Position__c
                  WHERE Status__c =: selectStatus
                  ORDER BY Name];
    }
  }
  
  public PageReference save() {
    update positions;
    PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
    pageRef.setRedirect(true); 
    return pageRef; 
  }
}