force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Application_deadline__c.field-meta.xml
<CustomField>
    <fullName>Application_deadline__c</fullName>
    <label>Application deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending...</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestChangePositionStatusTrigger.cls
@isTest
private class TestChangePositionStatusTrigger {
    @isTest
    static void TestChangePositionStatus() {
        Position__c position = new Position__c(Name = 'Test Position', Status__c = 'Open', Application_deadline__c = System.today().addDays(5));
        insert position;
        position.Status__c = 'Closed';
                
        Test.startTest();
            update position;
        Test.stopTest(); 

        List<Position__c> updatePositionDeadline = [SELECT Name, Status__c, Application_deadline__c FROM Position__c WHERE Id = :position.Id];
        System.debug('updatePositionDeadline --------> ' + updatePositionDeadline);
        System.assertEquals(System.today(), updatePositionDeadline.get(0).Application_deadline__c);
    }
}