force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Average_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_rating__c</fullName>
    <label>Average rating</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Number_of_reviews__c.field-meta.xml
<CustomField>
    <fullName>Number_of_reviews__c</fullName>
    <label>Number of reviews</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Rating this part of interview from 1 to 10</inlineHelpText>
    <label>Rating</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CountReviewTrigger.cls
public with sharing class CountReviewTrigger {
    public static void countReview (List<Review__c> reviewList) {
        Set<Id> jaIds = new Set<Id>();
        List<Job_Application__c> jaList = new List<Job_Application__c>();
        Decimal averageRating;

        for(Review__c review : reviewList){
            jaIds.add(review.Job_Application__c); 
        }
        List<Job_Application__c> jobAppList = [SELECT Id, Name, Number_of_reviews__c, (SELECT Id, Rating__c FROM Reviews__r) 
                                                FROM Job_Application__c 
                                                WHERE Id IN :jaIds];
        for(Job_Application__c ja : jobAppList){
            List<AggregateResult> groupedRes = [SELECT AVG(Rating__c)ar FROM Review__c WHERE Job_Application__c =: ja.Id];
            for(AggregateResult aggRes : groupedRes){
                averageRating = (Decimal)aggRes.get('ar'); 
            }
            ja.Number_of_reviews__c = ja.Reviews__r.size();
            ja.Average_rating__c = averageRating;
            jaList.add(ja);
            
        }
        update jaList;
    }

    public static void countReviewUpdate (List<Review__c> reviewList, Map<Id, Review__c> oldMap){
        Set<Id> jaIds = new Set<Id>();
        List<Job_Application__c> jaList = new List<Job_Application__c>();
        Decimal averageRating;

        for(Review__c review : reviewList){
                jaIds.add(review.Job_Application__c); 
            if(review.Job_Application__c != oldMap.get(review.Id).Job_Application__c){
                jaIds.add(oldMap.get(review.Id).Job_Application__c);  // old parent id 
            }
        }
        List<Job_Application__c> jobAppList = [SELECT Id, Name, Average_rating__c, Number_of_reviews__c, (SELECT Id, Rating__c FROM Reviews__r) 
                                               FROM Job_Application__c 
                                               WHERE Id IN :jaIds];
        for(Job_Application__c ja : jobAppList){
            List<AggregateResult> groupedRes = [SELECT AVG(Rating__c)ar FROM Review__c WHERE Job_Application__c =: ja.Id];
            for(AggregateResult aggRes : groupedRes){
                averageRating = (Decimal)aggRes.get('ar'); 
            }
            ja.Number_of_reviews__c = ja.Reviews__r.size();
            ja.Average_rating__c = averageRating;
            jaList.add(ja);
        }
        update jaList; 
    }
}