force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Average_rating__c.field-meta.xml
<CustomField>
    <fullName>Average_rating__c</fullName>
    <label>Average rating</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Number_of_reviews__c.field-meta.xml
<CustomField>
    <fullName>Number_of_reviews__c</fullName>
    <label>Number of reviews</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{000000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Rating this part of interview from 1 to 10</inlineHelpText>
    <label>Rating</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestCountReviewTrigger.cls
@isTest
private class TestCountReviewTrigger {
    @isTest
    static void TestReviewInsert() {
        Position__c position = new Position__c(Name = 'Test Position');
        insert position;
        Candidate__c candidate = new Candidate__c(Name = 'Test Name', First_Name__c = 'Test FName');
        insert candidate;
        Job_Application__c ja = new Job_Application__c(Candidate__c = candidate.Id, Position__c = position.Id);
        insert ja;
        Review__c review1 = new Review__c(Job_Application__c = ja.Id, Rating__c = 5);                                      
        insert review1;
        Review__c review2 = new Review__c(Job_Application__c = ja.Id, Rating__c = 9);  
        Review__c review3 = new Review__c(Job_Application__c = ja.Id, Rating__c = 4);  

        Test.startTest();                            
            insert review2;
            insert review3;
        Test.stopTest();

        List<Job_Application__c> countJAFields = [SELECT Name, Number_of_reviews__c, Average_rating__c FROM Job_Application__c WHERE Id = :ja.Id];
        System.debug('countJAFields --------> ' + countJAFields);
    }

    @isTest
    static void TestReviewDelete() {
        Position__c position = new Position__c(Name = 'Test Position');                                      
        insert position;
        Candidate__c candidate = new Candidate__c(Name = 'Test Name', First_Name__c = 'Test FName');
        insert candidate;
        Job_Application__c ja = new Job_Application__c(Candidate__c = candidate.Id, Position__c = position.Id);
        insert ja;
        Review__c review1 = new Review__c(Job_Application__c = ja.Id, Rating__c = 5);                                      
        insert review1;
        Review__c review2 = new Review__c(Job_Application__c = ja.Id, Rating__c = 9);                                      
        insert review2;

        Test.startTest();
            delete review1;
        Test.stopTest();

        List<Job_Application__c> countJAFields = [SELECT Name, Number_of_reviews__c, Average_rating__c FROM Job_Application__c WHERE Id = :ja.Id];
        System.debug('countJAFields --------> ' + countJAFields);
    }
}