force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Fieldset_Setting__mdt/Fieldset_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Fieldset Setting</label>
    <pluralLabel>Fieldset Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Fieldset_Setting__mdt/fields/Candidate_Fieldset_in_Card__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Fieldset_in_Card__c</fullName>
    <label>Candidate Fieldset in Card</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidatesForPositionHelperTest.cls
@isTest
private class CandidatesForPositionHelperTest {

    @isTest
    static void testGetCandidatesList (){        
        List <Job_Application__c> jobApp = CandidatesForPositionHelper.getCandidatesList('a017Q00000gbdqbQAA');
        System.assert(jobApp!=null);      
    }

    @isTest
    static void testGetCandidateForModal (){        
        List <Candidate__c> candidate = CandidatesForPositionHelper.getCandidateForModal('a007Q00000BUX8qQAH');
        System.assert(candidate!=null);      
    }

    @isTest
    static void testGetJobAppByCandidate (){        
        List <Job_Application__c> jobApp = CandidatesForPositionHelper.getJobAppByCandidate('a007Q00000BUX8qQAH');
        System.assert(jobApp!=null);      
    }

    @isTest
    static void testGetFieldSetForm(){
        List<String> newFieldList = CandidatesForPositionHelper.getFieldSetForm('Candidate__c', 'Candidate_card_interviewer');
        System.assertEquals(4, newFieldList.size());
    }
    
    @isTest
    static void testGetCurrentMetadataFieldSets() {
		List<Fieldset_Setting__mdt> mtdList = CandidatesForPositionHelper.getCurrentMetadataFieldSets('Recruiter');
        System.assertEquals('Candidate_card_recruiter', mtdList[0].Candidate_Fieldset_in_Card__c);
	}
}