force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fieldset_Setting__mdt/Fieldset_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Fieldset Setting</label>
    <pluralLabel>Fieldset Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Fieldset_Setting__mdt/fields/Candidate_Fieldset_in_Card__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Fieldset_in_Card__c</fullName>
    <label>Candidate Fieldset in Card</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fieldset_Setting__mdt/fields/Candidate_Fieldset_in_Modal__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Fieldset_in_Modal__c</fullName>
    <label>Candidate Fieldset in Modal</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fieldset_Setting__mdt/fields/Job_Application_Fieldset_in_Modal__c.field-meta.xml
<CustomField>
    <fullName>Job_Application_Fieldset_in_Modal__c</fullName>
    <label>Job Application Fieldset in Modal</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{000000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Position__c.Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidatesForPositionHelper.cls
public with sharing class CandidatesForPositionHelper {

    @AuraEnabled (cacheable=true)
    public static List<Job_Application__c> getCandidatesList(Id recordId) {
        String query = 'SELECT Name, Position__c, Candidate__r.Name, Candidate__r.First_Name__c '
                        + 'FROM Job_Application__c WHERE Position__c =: recordId';
        return Database.query(query);
    }  
    
    @AuraEnabled (cacheable=true)
    public static List<Candidate__c> getCandidateForModal(Id candidateId) {
        String query = 'SELECT Name, First_Name__c, (SELECT Id, Name FROM Job_Applications__r) '
                        + 'FROM Candidate__c WHERE Id =: candidateId';
        return Database.query(query);
    } 

    @AuraEnabled (cacheable=true)
    public static List<Job_Application__c> getJobAppByCandidate(Id candidateId) {
        String query = 'SELECT Id FROM Job_Application__c WHERE Candidate__c =: candidateId';
        return Database.query(query);
    }
    
    @AuraEnabled (cacheable=true)
    public static List<String> getFieldSetForm(String objectName, String fieldSetName) {
        Set<String> usedFields = new Set<String>();
            for(Schema.FieldSetMember fieldSet : Schema.getGlobalDescribe().get(objectName).getDescribe().fieldSets.getMap().get(fieldSetName).getFields()) {
                usedFields.add(fieldSet.getFieldPath());
            }
        List<String> fieldList = new List<String>(usedFields);
        System.debug('fieldList===> ' + fieldList);
        return fieldList;
    }

    @AuraEnabled (cacheable=true)
    public static List<Fieldset_Setting__mdt> getCurrentMetadataFieldSets(String profileApiName) {
        List<Fieldset_Setting__mdt> mdtList = [SELECT Candidate_Fieldset_in_Card__c, Candidate_Fieldset_in_Modal__c, Job_Application_Fieldset_in_Modal__c
                                               FROM Fieldset_Setting__mdt
                                               WHERE MasterLabel =: profileApiName];
        System.debug('mdtList===> ' + mdtList);
        return mdtList;
    }

}