force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_create_form_Setting__mdt/Candidate_create_form_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Candidate create-form Setting</label>
    <pluralLabel>Candidate create-form Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Candidate_create_form_Setting__mdt/fields/Candidate_Fieldset_create_form__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Fieldset_create_form__c</fullName>
    <label>Candidate Fieldset create-form</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CandidateCustomCreateFormHelperTest.cls
@isTest
public class CandidateCustomCreateFormHelperTest {
    
    @isTest
    static void testGetFieldSetForCreateForm(){
        List<String> newFieldList = CandidateCustomCreateFormHelper.getFieldSetForCreateForm('Candidate__c', 'Candidate_create_form');
        System.assertEquals(8, newFieldList.size());
    }
    
    @isTest
    static void testGetCurrentMetadataFieldSetsByForm() {
		List<Candidate_create_form_Setting__mdt> mtdList = CandidateCustomCreateFormHelper.getCurrentMetadataFieldSetsByForm();
        System.assertEquals('Candidate_create_form', mtdList[0].Candidate_Fieldset_create_form__c);
	}

}