force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_create_form_Setting__mdt/Candidate_create_form_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Candidate create-form Setting</label>
    <pluralLabel>Candidate create-form Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Candidate_create_form_Setting__mdt/fields/Candidate_Fieldset_create_form__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Fieldset_create_form__c</fullName>
    <label>Candidate Fieldset create-form</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminSettingsCanCustomCreateFormTest.cls
@isTest
private class AdminSettingsCanCustomCreateFormTest {
    
    @isTest
    static void testGetFieldSetApiNames() {
        List<String> listOfFieldSetApiNames = new List<String>();
        Schema.SObjectType sObjType = Schema.getGlobalDescribe().get('Candidate__c');
        Map<String, Schema.FieldSet> fieldSetNameToItsRecord = sObjType.getDescribe().fieldsets.getMap();
        listOfFieldSetApiNames.addAll( fieldSetNameToItsRecord.keySet() );
        System.assertEquals(AdminSettingsCandidateCustomCreateForm.getFieldSetApiNames('Candidate__c'), listOfFieldSetApiNames);
    }

    @isTest
    static void testGetCurrentFieldSetsByForm(){          
        Map<String, Candidate_create_form_Setting__mdt> fieldSetsByForm = AdminSettingsCandidateCustomCreateForm.getCurrentFieldSetsByForm();
        System.assertEquals(1, fieldSetsByForm.size());
    }

    @isTest
    static void testConstructDeploymentRequest() {
        Map<String, Candidate_create_form_Setting__mdt> customMetadataRecords = Candidate_create_form_Setting__mdt.getAll();
		Map<String, Candidate_create_form_Setting__mdt> customMetadataRecordsForUpdate = customMetadataRecords.deepClone();
		customMetadataRecordsForUpdate.get('Create_form_New_Candidate').Candidate_Fieldset_create_form__c = 'Candidate_create_form';
        Test.startTest();        
            Metadata.DeployContainer container = AdminSettingsCandidateCustomCreateForm.constructDeploymentRequest(customMetadataRecordsForUpdate);
        Test.stopTest();
        System.assertEquals(1, container.getMetadata().size());
    }

}